name: create-release

on:
  workflow_dispatch:
    inputs:
      version-string:
        type: string
        required: true

jobs:
  internal-create-release:
    uses: ./.github/workflows/internal-create-release@SetupWorkflows
    with:
      solution-file-path: 'Source/Starship-Expansion-Project.sln'
      use-ckan: true
      version-string: ${{ inputs.version-string }}
      artifacts: LICENSE* README* CHANGELOG*
